### ISSUE TITLE
Allow the user to decide the error response when access is denied.

### ISSUE THREAD

**Issue by kukv** [bright-room/feature-flag-spring-boot-starter#17]

**Comment by kukv** [comment]
https://datatracker.ietf.org/doc/html/rfc9457

**Comment by kukv** [comment]
- ステータスコートのみを返すパターン
- ステータスコードとテキストを返すパターン
- ステータスコードとRFC-9457に準拠したJsonを返すパターン
- ステータスコードと使う側が指定したJsonの形で返すパターン

**Comment by kukv** [comment]
```yaml
feature-flags:
  response:
    status-code: 405
    response-body:
      enabled: true
      text: "hogehoge"
      json:
        <key>: <value>
```
